settings:
  # level:  日志级别，支持 debug,info,warn,error等
  # format: 日志格式，支持 console,json
  # output: 输出位置，支持 stdout,stderr 或任意文件名，多个输出使用逗号分割
  log:
    level: info
    format: json
    output: stdout

  mysql:
    host: 192.168.48.151
    port: 3306
    username: root
    password: QiNqg[l.%;H>>rO9
    dbname: demo
    charset: utf8mb4